### ISSUE TITLE
小米平板Hyperos(Android14)测试已修复失效问题

### ISSUE THREAD

**Issue by Shadowshan** [jitcor/FakeScreen#1]
反馈一下，小米平板Hyperos(Android14)测试已修复失效问题。主要平板上面小米不给平板做游戏息屏挂机功能，正好这个模块可以解决。上一个版本测试了还是失效的，刚刚更新1.6后可以正常工作了。

**Comment by jitcor** [comment]
OKOK，感谢反馈
