### ISSUE TITLE
无法连接到 LSPosed

### ISSUE THREAD

**Issue by shibadogcap** [jitcor/FakeScreen#14]
我尝试在运行 Nothing OS 2.6 的 Nothing 手机(2) 上使用此模块，但即使我从 LSPosed 应用程序启用了该模块并重新启动，我仍收到错误“xConf is null”。我正在使用分叉的 LSPosed 版本 1.9.3。 （我用的是谷歌翻译）![Screenshot_20240921-214420.png](https://github.com/user-attachments/assets/f540f24e-1644-4167-bde6-a827a7dd0ef5)

**Comment by jitcor** [comment]
建议试试1.9.2

shibadogcap ***@***.***>于2024年9月21日 周六下午8:46写道：

**Comment by shibadogcap** [comment]
在我的环境中，当我尝试使用版本 1.9.2 时，Zygisk 不再启用。所以我使用的是1.9.3版本。

**Comment by jitcor** [comment]
Zygisk不再启用？

shibadogcap ***@***.***>于2024年9月22日 周日上午7:25写道：

**Comment by shibadogcap** [comment]
卸载版本 1.9.2 并安装 1.9.3 后，Zygisk 将再次启用。

**Comment by jitcor** [comment]
lsp跟zygisk应该没什么关联吧

shibadogcap ***@***.***>于2024年9月22日 周日上午7:36写道：

**Comment by shibadogcap** [comment]
应该是这样，但我唯一改变的是 LSPosed 的版本，所以这似乎是原因。很奇怪。

**Comment by jitcor** [comment]
其他模块能正常激活吗？

**Comment by jitcor** [comment]
或者可以试下这个版本：https://github.com/JingMatrix/LSPosed

**Comment by jitcor** [comment]
或者也可以试下： `adb uninstall com.google.android.art`

**Comment by shibadogcap** [comment]
通过更改 LSPosed 的版本并删除 ART 缓存解决了该问题。太感谢了！ ！
