### ISSUE TITLE
xConf is null

### ISSUE THREAD

**Issue by debianroot20200524** [jitcor/FakeScreen#15]
![Screenshot_20241020-182418_设置.png](https://github.com/user-attachments/assets/866fb7d0-9e3f-4baa-b1f8-975fd215e8e0)

![Screenshot_20241020-182315_FakeScreen.png](https://github.com/user-attachments/assets/9d533dab-342d-4e42-8f60-bb6dca382357)

![Screenshot_20241020-182331_LSPosed.png](https://github.com/user-attachments/assets/dd0665a6-8c78-434b-b058-d888d9f8a7d8)

**Comment by jitcor** [comment]
#14

**Comment by jitcor** [comment]
https://github.com/jitcor/FakeScreen/issues/14
