### ISSUE TITLE
播放抖音的时候，按了电源键就不播放了，是不是应该黑屏状态继续播放吗

### ISSUE THREAD

**Issue by iaston** [jitcor/FakeScreen#2]
我不太明白这个软件是否可以实现，但是如果能够在息屏的情况下，也听抖音好像也是不错的一个。

小米澎湃系统

**Comment by jitcor** [comment]
那说明模块没生效

**Comment by iaston** [comment]
这样的设置正确吗？
![Screenshot_2023-12-20-09-56-52-473_com android shell](https://github.com/jitcor/FakeScreen/assets/11807657/9e9ea220-d879-4bde-b097-d6e0e293a1f4)
![Screenshot_2023-12-20-09-56-28-862_me neversleep plusplus](https://github.com/jitcor/FakeScreen/assets/11807657/088aa5fe-fc08-47c1-bfd0-15ebc20302be)

**Comment by jitcor** [comment]
![image](https://github.com/jitcor/FakeScreen/assets/27600008/e90e27ee-f08c-43b7-af86-d081f8c2a978)
