### ISSUE TITLE
System's screen off timer "turns off" (and lock ) screen during FAKESCREEN

### ISSUE THREAD

**Issue by DaveRamirezCodes** [jitcor/FakeScreen#4]
This app is great, works great and and it does exactly what it says it will do.

But it has only one issue: when you activate FAKESCREEN and press the power button,  The system actually remains active and does not lock, but The automatic screen off timer continues to run causing the screen to actually turn off during FAKESCREEN...I'm forced to use along with FAKESCREEN other things lik the QStile (QuickSetting Tile) "CAFFEINE"or other methods (like stay awake on Developer options) to delay or disable automatic screen off to avoid this problems... Please, to solve this issue you could integrate a function that temporarily disables the automatic turning off of the screen (as does QStile CAFFEINE) when the FAKESCREEN service is activated...

If you need the mo device data, here they are:

ONEPLUS 9 PRO (SNAPDRAGON 888)
EVOLUTION X (AOSP Based Android 13 QPR3)
Security patch: 5 November 2023
Magisk 26.4
Lsposed 1.9.2 (zygisk version)

**Comment by jitcor** [comment]
1.7 is supported  [1.7](https://github.com/jitcor/FakeScreen/releases/tag/1.7)
