### ISSUE TITLE
1.7.1 already compiled APK

### ISSUE THREAD

**Issue by DaveRamirezCodes** [jitcor/FakeScreen#6]
English Version :
First of all, thank you for immediately solving the problem reported for version 1.6.1 and for immediately producing version 1.7.1 with the fix. Your work is fantastic and very useful: this tool solves a problem that no one has ever managed to solve very effectively in a short time and significantly improves the experience of many users. Having said this, I ask you for one last effort... forgive me the inconvenience of another request, and I hope that out of kindness you will help us: could you add the compiled apk of version 1.7.1 to the releases? Or (since unfortunately like many other users 😅 I don't know how to compile an apk with Gradle and/or Github, ) you could give me an explanation on how to compile the APK myself. Thanks in advance

Translation in Chinese (simplified) :
翻译成中文（简体）:
首先，感谢您立即修复所报告的 1.6.1 版本问题并立即创建更正后的 1.7.1 版本。你的工作非常棒而且非常有用——这个工具以真正有效的方式解决了一个从未有人解决过的问题，并极大地改善了许多用户的体验。说到这里，我请你做最后的绝望的努力……很抱歉新问题带来的不便，希望你能帮助我们：你能添加已经编译好的1.7.1版本的apk吗？或者（不幸的是，像许多其他用户一样，我不知道如何使用 Gradle 和/或 Github 编译 apk）您可以向我解释如何编译 APK。提前致谢

**Comment by jitcor** [comment]
1.7.1 is currently tested to cause other, more serious problems that are not fixed yet, I can send you a finished product if you need it:
[1.7.1_20240127_123100_release.apk.zip](https://github.com/jitcor/FakeScreen/files/15124545/1.7.1_20240127_123100_release.apk.zip)

**Comment by jitcor** [comment]
https://github.com/jitcor/FakeScreen/releases/tag/1.7
